version: '3.4'
services:
  mlsp-aesthetic-score-predictor:
    image: cribin/mlsp-aesthetic-score-predictor:dev
    ports:
      - '5001:5001'
    volumes:
      - aesthetics-content-storage:/content-storage
  deep-face-emotion-predictor:
    image: cribin/deepface-emotion-predictor:dev
    ports:
      - '5002:5002'
    volumes:
      - aesthetics-content-storage:/content-storage
  upload-extraction-manager:
    image: cribin/upload-and-extraction-manager:dev
    volumes:
      - aesthetics-content-storage:/content-storage
#      - /local/home/cribin/Documents/AestheticsBackup/UploadAndExtractionManager/test_config:/shared_config
    ports:
      - '5003:5003'
    depends_on:
      - "deep-face-emotion-predictor"
      - "mlsp-aesthetic-score-predictor"
volumes:
  aesthetics-content-storage:
