version: '3.4'
services:
  mlsp-aesthetic-score-predictor:
    network_mode: host
    build:
      network: host
      dockerfile: Dockerfile
      context: /local/home/cribin/Documents/AestheticsBackup/Mlsp_Local_Installation/MlspAestheticScorePredictor
    ports:
      - '5001:5001'
    volumes:
      - aesthetics-content-storage:/content-storage
  deep-face-emotion-predictor:
    network_mode: host
    build:
      network: host
      dockerfile: Dockerfile
      context: /local/home/cribin/Documents/AestheticsBackup/DeepFaceEmotionPredictor
    ports:
      - '5002:5002'
    volumes:
      - aesthetics-content-storage:/content-storage
  upload-extraction-manager:
    network_mode: host
    build:
      network: host
      dockerfile: Dockerfile
      context: ./
    volumes:
      - aesthetics-content-storage:/content-storage
    ports:
      - '5003:5003'
volumes:
  aesthetics-content-storage:
