version: '3.4'
services:
  mlsp-aesthetic-score-predictor:
    image: cribin/mlsp-aesthetic-score-predictor:dev
    ports:
      - '5001:5001'
    volumes:
      - aesthetics-content-storage:/content-storage
  deep-face-emotion-predictor:
    image: cribin/deepface-emotion-predictor:dev
    ports:
      - '5007:5007'
    volumes:
      - aesthetics-content-storage:/content-storage
  hecate-image-and-video-metrics-predictor:
    image: cribin/hecate-image-and-video-metrics-predictor:dev
    ports:
      - '5004:5004'
    volumes:
        - aesthetics-content-storage:/content-storage
  upload-extraction-manager:
    image: cribin/upload-and-extraction-manager:dev
    volumes:
      - aesthetics-content-storage:/content-storage
      - /local/home/cribin/Documents/AestheticsBackup/UploadAndExtractionManager/cineast/log.txt:/uploadAndExtractionManager/cineast/log.txt
      - /local/home/cribin/Documents/AestheticsBackup/UploadAndExtractionManager/cineast/example_job.json:/uploadAndExtractionManager/cineast/example_job.json
    ports:
      - '5003:5003'
      - '4567:4567'
#  vitrivr-ng-webinterface:
#    image: cribin/vitrivr-web-interface-angular-app:dev
#    volumes:
#      - aesthetics-content-storage:/content-storage
##      - /local/home/cribin/Documents/AestheticsBackup/Aesthetics_ContentViewer_Main/Vitrivr_Local_Installation/vitrivr-ng/src/config.json:/vitrivr-webinterface/src/config.json
#    depends_on:
#      - 'upload-extraction-manager'
#    ports:
#      - '4200:4200'
volumes:
  aesthetics-content-storage:
